name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          export CYPRESS_INSTALL_BINARY=0
          npm ci --unsafe-perm

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run e2e tests (Cypress)
        run: npm run e2e
        env:
          CI: true
